package: yform_gridblock 
version: '1.0.0'
author: YourName
supportpage: https://github.com/yourgithub/yform_gridblock

page:
    title: 'YForm Gridblock'
    perm: admin
    subpages:
        settings: { title: 'Settings' }

requires:
    redaxo: '^5.12.0'
    php:
        version: '>=7.3'
    packages:
        yform: '^4.0.0'
        gridblock: '^1.0.0'
